/**
 * Compiles `src/ui/**\/*.tsx` through babel-preset-solid in SSR mode into sibling
 * `*.gen.js` files, which the Elysia routes import.
 *
 * Wrangler bundles with esbuild and exposes no plugin hook, so Solid's JSX compiler
 * cannot run inside the Worker build. Precompiling here ships the pages as compiled SSR
 * templates - string concatenation with no runtime JSX factory - which is both the
 * fastest option and the only one wrangler can consume.
 *
 * Output lands beside each source so relative imports of plain `.ts` helpers resolve
 * identically before and after compilation.
 */
import { transformAsync } from "@babel/core";
// @ts-expect-error - babel-preset-solid ships no types
import solid from "babel-preset-solid";
import typescript from "@babel/preset-typescript";
import { Glob } from "bun";
import { dirname, join, relative, resolve } from "node:path";
import { mkdir, unlink } from "node:fs/promises";

const UI_DIR = import.meta.dir;

/**
 * Geist is the face - one variable file covering every weight. It is embedded as base64
 * and served from the Worker with an immutable cache rather than inlined into the CSS: a
 * data URI would ride in every HTML response, where a served file is fetched once and
 * cached forever.
 */
const FONTS: Record<string, string> = {
  geist: "node_modules/@fontsource-variable/geist/files/geist-latin-wght-normal.woff2",
};

/**
 * Stamps the commit being built into the bundle so a deploy can be verified against it.
 * A wrangler upload has shipped stale code before; without a marker in the artifact there
 * is no way to tell a successful deploy from a successful upload of the wrong thing.
 */
async function buildInfo() {
  const proc = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"]);
  const commit = proc.success ? new TextDecoder().decode(proc.stdout).trim() : "unknown";
  // The release version comes from package.json so /health cannot drift from the tag.
  const { version } = (await Bun.file(join(UI_DIR, "..", "..", "package.json")).json()) as { version: string };
  await Bun.write(
    join(UI_DIR, "..", "build-info.gen.ts"),
    `// Generated by src/ui/build.ts. Do not edit.\nexport const BUILD = { version: "${version}", commit: "${commit}", builtAt: "${new Date().toISOString()}" };\n`
  );
}

/**
 * Hashes the one inline script so the CSP can admit it by value. Generated rather than
 * hand-written: a stale hash would not fail loudly, it would silently stop the script from
 * running and leave the eye hidden, which is exactly the failure mode nobody notices.
 */
async function buildPeekHash() {
  const { PEEK_SCRIPT } = await import("./peek");
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(PEEK_SCRIPT));
  await Bun.write(
    join(UI_DIR, "peek.gen.ts"),
    `// Generated by src/ui/build.ts. Do not edit.\nexport const PEEK_SHA256 = "sha256-${Buffer.from(digest).toString("base64")}";\n`
  );
}

/**
 * Bundles each MCP App's client module into a single self-contained HTML string.
 *
 * MCP Apps render in a sandboxed iframe under a deny-by-default CSP, so the app cannot
 * fetch anything: script, styles and markup all have to be in the one document. Bun.build
 * does the bundling (the project has no vite and does not want one), and the result is
 * inlined into a generated module because a Worker has no filesystem to read it from at
 * request time.
 */
async function buildMcpApps() {
  const { MCP_UI_APPS } = await import("../mcp/ui/registry");
  const { appShell } = await import("../mcp/ui/shell");
  const outDir = join(UI_DIR, "..", "mcp", "ui");

  const entries: string[] = [];
  for (const app of MCP_UI_APPS) {
    const entry = join(outDir, "apps", `${app.id}.client.ts`);
    const built = await Bun.build({
      entrypoints: [entry],
      target: "browser",
      format: "esm",
      minify: true,
    });

    if (!built.success) {
      throw new Error(`MCP app "${app.id}" failed to build:\n${built.logs.join("\n")}`);
    }

    const script = await built.outputs[0]!.text();
    // The script is embedded in a <script> element, so a literal </script> anywhere in it
    // (in a string, a regex, anywhere) would close the tag early and break the document.
    const safe = script.replace(/<\/script/gi, "<\\/script");
    const html = appShell(app.title, safe);
    entries.push(`  ${JSON.stringify(app.id)}: ${JSON.stringify(html)},`);
  }

  await Bun.write(
    join(outDir, "apps.gen.ts"),
    `// Generated by src/ui/build.ts. Do not edit.\nexport const APP_HTML: Record<string, string> = {\n${entries.join("\n")}\n};\n`
  );

  return MCP_UI_APPS.length;
}

async function buildFonts() {
  const entries: string[] = [];
  for (const [name, path] of Object.entries(FONTS)) {
    const bytes = await Bun.file(join(process.cwd(), path)).arrayBuffer();
    entries.push(`  ${name}: "${Buffer.from(bytes).toString("base64")}",`);
  }
  await Bun.write(
    join(UI_DIR, "fonts.gen.ts"),
    `// Generated by src/ui/build.ts. Do not edit.\nexport const FONTS: Record<string, string> = {\n${entries.join("\n")}\n};\n`
  );
  return Object.keys(FONTS).length;
}

async function buildIcon() {
  const bytes = await Bun.file(join(UI_DIR, "..", "..", "public", "mailwarden.png")).arrayBuffer();
  await Bun.write(
    join(UI_DIR, "icon.gen.ts"),
    `// Generated by src/ui/build.ts. Do not edit.\nexport const ICON_PNG_B64 = "${Buffer.from(bytes).toString("base64")}";\n`
  );
}

export async function buildUi() {
  await buildInfo();
  await buildFonts();
  await buildIcon();
  await buildPeekHash();
  const apps = await buildMcpApps();
  const sources = [...new Glob("**/*.tsx").scanSync({ cwd: UI_DIR })];
  const compiled = new Set(sources.map((s) => resolve(UI_DIR, s)));

  // Drop stale output so a deleted component cannot keep shipping.
  for (const stale of new Glob("**/*.gen.js").scanSync({ cwd: UI_DIR })) {
    await unlink(join(UI_DIR, stale));
  }

  for (const source of sources) {
    const absolute = join(UI_DIR, source);
    const code = await Bun.file(absolute).text();

    const result = await transformAsync(code, {
      filename: absolute,
      babelrc: false,
      configFile: false,
      presets: [typescript, [solid, { generate: "ssr", hydratable: false }]],
    });

    if (!result?.code) throw new Error(`babel produced no output for ${source}`);

    // A relative specifier that names another compiled component must point at its
    // generated sibling; specifiers naming plain .ts helpers are left alone.
    const emitted = result.code.replace(
      /(from\s+["'])(\.{1,2}\/[^"']+?)(["'])/g,
      (match, head: string, spec: string, tail: string) => {
        const bare = spec.replace(/\.(tsx|jsx)$/, "");
        return compiled.has(resolve(dirname(absolute), `${bare}.tsx`))
          ? `${head}${bare}.gen.js${tail}`
          : match;
      }
    );

    const target = join(UI_DIR, source.replace(/\.tsx$/, ".gen.js"));
    await mkdir(dirname(target), { recursive: true });
    await Bun.write(target, emitted);
  }

  return { count: sources.length, dir: relative(process.cwd(), UI_DIR), apps };
}

if (import.meta.main) {
  const { count, dir, apps } = await buildUi();
  console.log(`ui: compiled ${count} component${count === 1 ? "" : "s"} -> ${dir}/*.gen.js`);
  console.log(`mcp: bundled ${apps} app${apps === 1 ? "" : "s"} -> src/mcp/ui/apps.gen.ts`);
}
